// Code generated by mockery v2.53.0. DO NOT EDIT.

package mclickhouse

import (
	context "context"

	rclickhouse "github.com/0LuigiCode0/hezzl/internal/infrastructure/repository/clickhouse"
	mock "github.com/stretchr/testify/mock"
)

// IClickHouse is an autogenerated mock type for the IClickHouse type
type IClickHouse struct {
	mock.Mock
}

type IClickHouse_Expecter struct {
	mock *mock.Mock
}

func (_m *IClickHouse) EXPECT() *IClickHouse_Expecter {
	return &IClickHouse_Expecter{mock: &_m.Mock}
}

// InsertGoodsLogBatch provides a mock function with given fields: ctx
func (_m *IClickHouse) InsertGoodsLogBatch(ctx context.Context) (rclickhouse.IBatch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InsertGoodsLogBatch")
	}

	var r0 rclickhouse.IBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (rclickhouse.IBatch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) rclickhouse.IBatch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rclickhouse.IBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClickHouse_InsertGoodsLogBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertGoodsLogBatch'
type IClickHouse_InsertGoodsLogBatch_Call struct {
	*mock.Call
}

// InsertGoodsLogBatch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IClickHouse_Expecter) InsertGoodsLogBatch(ctx interface{}) *IClickHouse_InsertGoodsLogBatch_Call {
	return &IClickHouse_InsertGoodsLogBatch_Call{Call: _e.mock.On("InsertGoodsLogBatch", ctx)}
}

func (_c *IClickHouse_InsertGoodsLogBatch_Call) Run(run func(ctx context.Context)) *IClickHouse_InsertGoodsLogBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IClickHouse_InsertGoodsLogBatch_Call) Return(_a0 rclickhouse.IBatch, _a1 error) *IClickHouse_InsertGoodsLogBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClickHouse_InsertGoodsLogBatch_Call) RunAndReturn(run func(context.Context) (rclickhouse.IBatch, error)) *IClickHouse_InsertGoodsLogBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewIClickHouse creates a new instance of IClickHouse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClickHouse(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClickHouse {
	mock := &IClickHouse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
