// Code generated by mockery v2.53.0. DO NOT EDIT.

package mpostgres

import (
	context "context"

	dpostgres "github.com/0LuigiCode0/hezzl/internal/domain/postgres"
	mock "github.com/stretchr/testify/mock"
)

// ITx is an autogenerated mock type for the ITx type
type ITx struct {
	mock.Mock
}

type ITx_Expecter struct {
	mock *mock.Mock
}

func (_m *ITx) EXPECT() *ITx_Expecter {
	return &ITx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx
func (_m *ITx) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ITx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type ITx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ITx_Expecter) Commit(ctx interface{}) *ITx_Commit_Call {
	return &ITx_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *ITx_Commit_Call) Run(run func(ctx context.Context)) *ITx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ITx_Commit_Call) Return(_a0 error) *ITx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ITx_Commit_Call) RunAndReturn(run func(context.Context) error) *ITx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// EndTx provides a mock function with given fields: ctx, err
func (_m *ITx) EndTx(ctx context.Context, err error) {
	_m.Called(ctx, err)
}

// ITx_EndTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndTx'
type ITx_EndTx_Call struct {
	*mock.Call
}

// EndTx is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
func (_e *ITx_Expecter) EndTx(ctx interface{}, err interface{}) *ITx_EndTx_Call {
	return &ITx_EndTx_Call{Call: _e.mock.On("EndTx", ctx, err)}
}

func (_c *ITx_EndTx_Call) Run(run func(ctx context.Context, err error)) *ITx_EndTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(error))
	})
	return _c
}

func (_c *ITx_EndTx_Call) Return() *ITx_EndTx_Call {
	_c.Call.Return()
	return _c
}

func (_c *ITx_EndTx_Call) RunAndReturn(run func(context.Context, error)) *ITx_EndTx_Call {
	_c.Run(run)
	return _c
}

// GetGoods provides a mock function with given fields: ctx, limit, offset
func (_m *ITx) GetGoods(ctx context.Context, limit int, offset int) ([]*dpostgres.Good, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetGoods")
	}

	var r0 []*dpostgres.Good
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*dpostgres.Good, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*dpostgres.Good); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dpostgres.Good)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITx_GetGoods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoods'
type ITx_GetGoods_Call struct {
	*mock.Call
}

// GetGoods is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *ITx_Expecter) GetGoods(ctx interface{}, limit interface{}, offset interface{}) *ITx_GetGoods_Call {
	return &ITx_GetGoods_Call{Call: _e.mock.On("GetGoods", ctx, limit, offset)}
}

func (_c *ITx_GetGoods_Call) Run(run func(ctx context.Context, limit int, offset int)) *ITx_GetGoods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ITx_GetGoods_Call) Return(_a0 []*dpostgres.Good, _a1 error) *ITx_GetGoods_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITx_GetGoods_Call) RunAndReturn(run func(context.Context, int, int) ([]*dpostgres.Good, error)) *ITx_GetGoods_Call {
	_c.Call.Return(run)
	return _c
}

// GetGoodsMeta provides a mock function with given fields: ctx
func (_m *ITx) GetGoodsMeta(ctx context.Context) (*dpostgres.Meta, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGoodsMeta")
	}

	var r0 *dpostgres.Meta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*dpostgres.Meta, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *dpostgres.Meta); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dpostgres.Meta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITx_GetGoodsMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoodsMeta'
type ITx_GetGoodsMeta_Call struct {
	*mock.Call
}

// GetGoodsMeta is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ITx_Expecter) GetGoodsMeta(ctx interface{}) *ITx_GetGoodsMeta_Call {
	return &ITx_GetGoodsMeta_Call{Call: _e.mock.On("GetGoodsMeta", ctx)}
}

func (_c *ITx_GetGoodsMeta_Call) Run(run func(ctx context.Context)) *ITx_GetGoodsMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ITx_GetGoodsMeta_Call) Return(_a0 *dpostgres.Meta, _a1 error) *ITx_GetGoodsMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITx_GetGoodsMeta_Call) RunAndReturn(run func(context.Context) (*dpostgres.Meta, error)) *ITx_GetGoodsMeta_Call {
	_c.Call.Return(run)
	return _c
}

// InsertGood provides a mock function with given fields: ctx, in
func (_m *ITx) InsertGood(ctx context.Context, in *dpostgres.InsertGood) (*dpostgres.Good, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for InsertGood")
	}

	var r0 *dpostgres.Good
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dpostgres.InsertGood) (*dpostgres.Good, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dpostgres.InsertGood) *dpostgres.Good); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dpostgres.Good)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dpostgres.InsertGood) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITx_InsertGood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertGood'
type ITx_InsertGood_Call struct {
	*mock.Call
}

// InsertGood is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dpostgres.InsertGood
func (_e *ITx_Expecter) InsertGood(ctx interface{}, in interface{}) *ITx_InsertGood_Call {
	return &ITx_InsertGood_Call{Call: _e.mock.On("InsertGood", ctx, in)}
}

func (_c *ITx_InsertGood_Call) Run(run func(ctx context.Context, in *dpostgres.InsertGood)) *ITx_InsertGood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dpostgres.InsertGood))
	})
	return _c
}

func (_c *ITx_InsertGood_Call) Return(_a0 *dpostgres.Good, _a1 error) *ITx_InsertGood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITx_InsertGood_Call) RunAndReturn(run func(context.Context, *dpostgres.InsertGood) (*dpostgres.Good, error)) *ITx_InsertGood_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGood provides a mock function with given fields: ctx, id
func (_m *ITx) RemoveGood(ctx context.Context, id int) (*dpostgres.Good, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGood")
	}

	var r0 *dpostgres.Good
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*dpostgres.Good, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *dpostgres.Good); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dpostgres.Good)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITx_RemoveGood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGood'
type ITx_RemoveGood_Call struct {
	*mock.Call
}

// RemoveGood is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ITx_Expecter) RemoveGood(ctx interface{}, id interface{}) *ITx_RemoveGood_Call {
	return &ITx_RemoveGood_Call{Call: _e.mock.On("RemoveGood", ctx, id)}
}

func (_c *ITx_RemoveGood_Call) Run(run func(ctx context.Context, id int)) *ITx_RemoveGood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ITx_RemoveGood_Call) Return(_a0 *dpostgres.Good, _a1 error) *ITx_RemoveGood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITx_RemoveGood_Call) RunAndReturn(run func(context.Context, int) (*dpostgres.Good, error)) *ITx_RemoveGood_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *ITx) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ITx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type ITx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ITx_Expecter) Rollback(ctx interface{}) *ITx_Rollback_Call {
	return &ITx_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *ITx_Rollback_Call) Run(run func(ctx context.Context)) *ITx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ITx_Rollback_Call) Return(_a0 error) *ITx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ITx_Rollback_Call) RunAndReturn(run func(context.Context) error) *ITx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGood provides a mock function with given fields: ctx, in
func (_m *ITx) UpdateGood(ctx context.Context, in *dpostgres.UpdateGood) (*dpostgres.Good, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGood")
	}

	var r0 *dpostgres.Good
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dpostgres.UpdateGood) (*dpostgres.Good, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dpostgres.UpdateGood) *dpostgres.Good); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dpostgres.Good)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dpostgres.UpdateGood) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITx_UpdateGood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGood'
type ITx_UpdateGood_Call struct {
	*mock.Call
}

// UpdateGood is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dpostgres.UpdateGood
func (_e *ITx_Expecter) UpdateGood(ctx interface{}, in interface{}) *ITx_UpdateGood_Call {
	return &ITx_UpdateGood_Call{Call: _e.mock.On("UpdateGood", ctx, in)}
}

func (_c *ITx_UpdateGood_Call) Run(run func(ctx context.Context, in *dpostgres.UpdateGood)) *ITx_UpdateGood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dpostgres.UpdateGood))
	})
	return _c
}

func (_c *ITx_UpdateGood_Call) Return(_a0 *dpostgres.Good, _a1 error) *ITx_UpdateGood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITx_UpdateGood_Call) RunAndReturn(run func(context.Context, *dpostgres.UpdateGood) (*dpostgres.Good, error)) *ITx_UpdateGood_Call {
	_c.Call.Return(run)
	return _c
}

// NewITx creates a new instance of ITx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITx(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITx {
	mock := &ITx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
